models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

models/Users.php
<?php
/**
 * User: Svarg
 * Date: 30.11.2020
 * Time: 11:33
 */

namespace app\models;

use yii\db\ActiveRecord;

class Users extends ActiveRecord
{

    public static function getPartners($id){
        $users = self::find()->where('id='.$id)->all();
        foreach ($users as $user){
            if(!empty($user->partner_id)){
                $ar[] = self::find()->where('id='.$user->partner_id)->all();
            }
        }
        return self::find()->where('id='.$id)->all();

    }
    public function getAccounts(){
        return $this->hasMany(Accounts::className(),['client_uid'=>'client_uid']);
    }

}

controllers/UsersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 30.11.2020
 * Time: 11:46
 */

namespace app\controllers;

use Yii;
use app\components\ClientChild;
use app\components\ClientParent;
use app\models\Partners;
use app\models\Users;
use yii\web\Controller;

class UsersController extends Controller
{
    public function actionIndex(){
        $this->layout='tifia';
        $client = new ClientParent(123);
        $clients = $this->partners($client);
//        echo  $clients->operation();
        return $this->render('index',['data'=>$clients]);

    }

    function actionVolume(){
        $this->layout='tifia';
        //        SELECT u.id, a.client_uid, t.volume*t.coeff_h*t.coeff_cr vol
        //FROM users u
        //LEFT JOIN accounts a ON a.client_uid=u.client_uid
        //LEFT JOIN trades t ON t.login=a.login
        //WHERE u.id=123
        //        AND t.close_time BETWEEN '2019-03-01' AND '2019-03-31'
        //        ;

        $client = new ClientParent(123);
        $clients = $this->partners($client);
       // $sum = $clients->volumes('2019-03-01','2019-03-02');


//        $accounts = $client->getClient()->getAccounts()->all();
//        $sum = 0;
//        foreach ($accounts as $account){
//          $trades = $account->getTradesBetween('2019-03-01','2019-03-31');
//            foreach ($trades as $trade){
//                $sum += $trade->volume*$trade->coeff_h*$trade->coeff_cr;
//            }
//        }

//        $rows = (new \yii\db\Query())
////            ->select(['u.id', 'a.client_uid','t.volume*t.coeff_h*t.coeff_cr vol'])
//            ->select(['u.id as id', 'a.client_uid as client_uid','t.volume as volume','t.coeff_h as coeff_h','t.coeff_cr as coeff_cr'])
//            ->from('users u')
//            ->leftJoin('accounts a','a.client_uid=u.client_uid')
//            ->leftJoin('trades t','t.login=a.login')
//            ->where(['between','t.close_time','2019-03-01','2019-03-31'])
//            ->andWhere(['u.id' => $client->getClient()->id])
//            ->all();
//
//        $sum = 0;
//        foreach ($rows as $row){
//            $sum += $row['volume']*$row['coeff_h']*$row['coeff_cr'];
//        }
        return $this->render('volume',['data'=>$clients]);

    }
    function actionVolumesId(){
        $request = Yii::$app->request;
        $id = $request->get('key');
        $client = new ClientParent($id);
        $start='2019-03-01';
        $end = '2019-03-31';
//        var_dump($client->volumesId($start,$end));
        return  $client->volumesId($start,$end);

    }

    function actionLevel(){
        $this->layout='tifia';
        $client = new ClientParent(123);
        $clients = $this->partners($client);
        return $this->render('level',['data'=>$clients]);
    }

    function actionCount(){
        $this->layout('tifia');
        $client = new ClientParent(123);
        var_dump($client->countClient());
    }

    private  function partners($client){
        $user_temp = $client->getClient();
        $parents = Users::find()->where('partner_id='.$user_temp->client_uid)->all();
        if(!empty($parents)){
            foreach ($parents as $user){
                //var_dump($user->id);
                $client->add($this->partners(new ClientParent($user->id)));
            }
        }else{
            $client->add(new ClientChild($user_temp->id));
        }
        return $client;
    }

//    private function partners($client_uid){
////        $users = [];
//        $clients = new ClientParent(123);
//        foreach (Users::find()->where('partner_id='.$client_uid)->all() as $user){
//            if(!empty(Users::find()->where('partner_id='.$user->client_uid)->all())){
//                //$users[$user->client_uid][] = $this->partners($user->client_uid);
//                $clients->add($this->partners($user->client_uid));
//                $clients->add($this->partners($user->client_uid));
//
//            }else{
//                $users[]=[$user->client_uid] ;
//            }
//        }
//        return $users;
//    }

}

views/users/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 30.11.2020
 * Time: 11:54
 */
$this->title = 'ТИФИЯ-test';
?>

<div class="index">
    <div class="jumbotron">
        <h1>посчитать количество прямых рефералов и количество всех рефералов клиента</h1>
    </div>
    <div class="row" >
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <?php
            echo $data->operation();
            ?>
        </div>
        <div class="col-sm-4"></div>
    </div>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <span>Кол-во прямыми рефералами:</span>
            <?php
            echo $data->countClient();
            ?>
        </div>
        <div class="col-sm-4"></div>
    </div>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <span>Кол-во всего:</span>
            <?php
            echo $data->countClientAll();
            ?>
        </div>
        <div class="col-sm-4"></div>
    </div>

</div>

views/users/level.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 30.11.2020
 * Time: 11:54
 */
$this->title = 'ТИФИЯ-test';
?>

<div class="index">
    <div class="jumbotron">
        <h1>посчитать количество уровней реферальной сетки</h1>
    </div>
    <div class="row" >
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <span>Кол-во уровней реферальной сетки:</span>
            <?php
            echo $data->level()-1;
            ?>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>

views/users/volume.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 30.11.2020
 * Time: 11:54
 */
$this->title = 'ТИФИЯ-test';
?>

<div class="index">
    <div class="jumbotron">
        <h1>посчитать количество уровней реферальной сетки</h1>
    </div>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <span>Кол-во уровней реферальной сетки:</span>
            <?php
            foreach ($data->logins() as $key => $val) {
                ?>
                <div class="hidden child" data-key="<?php echo $key ?>" data-val="<?php echo $val ?>"></div>
                <?php
            }
            ?>
        </div>
        <div class="col-sm-4"></div>
    </div>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
           <table id="voluem">
               <tr>
                   <th>id</th>
                   <th>vol</th>
               </tr>
           </table>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function(){
        $.ajax({
            url:'<?php echo \yii\helpers\Url::to(['users/volumes-id']) ?>',
            data: 'key='+<?php echo $data->getClient()->id ?>,
            success: function(data){
                $('#voluem').before('<tr><td><?php echo $data->getClient()->id ?></td><td></td>'+data+'</tr>')
            }
        });
        for(i=0; i < $('.child').length; i++)
    {
        console.log($('.child').eq(i).data('key'));
        $.ajax({
            url:'<?php echo \yii\helpers\Url::to(['users/volumes-id']) ?>',
            data: 'key='+$('.child').eq(i).data('key'),
            success: function(data){
                $('#voluem').before('<tr><td>'+$('.child').eq(i).data('key')+'</td><td></td>'+data+'</tr>')
            }
        });

    }
    // console.log($('.child').data('key'));
    })
</script>